[package]
name = "cg-coop"
version = "0.1.0"
edition = "2024"

[dependencies]
glium = "0.35.0"
glam = "0.30.9"
gltf = "1.4.1"
imgui = "0.12.0"
imgui-glium-renderer = "0.13.0"
imgui-winit-support = "0.13.0"
image = "0.25.9"
tobj = "4.0"
glutin = "0.32.3"
